version: '3.8'

services:

  frontend:
    depends_on:
      - backend
    build: ./frontend
    ports:
      - 8080:8080

  backend:
    depends_on:
      - mongo-express
    build: ./backend
    ports:
      - 4000:4000
    environment:
      - DB_URL = mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db/war
  
  mongo-express:
    depends_on:
      - db
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER: db

  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
          - war:/data/db

volumes:
  war: