version: '3.8'

services:

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8080:8080

  backend:
    depends_on:
      - mongo-express
    build: ./backend
    ports:
      - 4000:4000
    environment:
      - DB_URL=mongodb://db/war
  
  mongo-express:
    image: mongo-express
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - war:/data/db

volumes:
  war: